version: '3'
services:
  phantom_tank:
    image: phantom_tank:latest
    container_name: phantom_tank
    restart: unless-stopped
    ports:
      - "15000:5000"
    volumes:
        #填写自己宿主机的路径
      - :path/logs:/app/python/logs
      - :path/images:/app/python/images
    environment:
      - TZ=Asia/Shanghai
      #文件大小限制
      - FILE_SIZE_LIMIT=30
      #每分钟访问限制
      - MAX_REQUESTS_PER_MINUTE=10
